### ISSUE TITLE
Option to ignore #bibliography and add words to the dictionary

### ISSUE THREAD

**Issue by michihupf** [antonWetzel/typst-languagetool#40]
Writing in german but having a lot of english references i get a LOT of useless spelling mistakes on my bibliography. It would be nice if this could be deactivated.

Also a nice feature would be be able to add domain specific words to the dictionary. I always find myself looking at warnings that are obviously correct (false positives on domain specific knowledge).

Also please let me know if this is something that is already possible, I have not found any documentation regarding this (Edit: I found the example for vscode but that doesn't really translate into the helix config)

**Comment by antonWetzel** [comment]
Maybe you can change the language for you bibliography
```typst
#{
    // not tested
    set text(lang: "en", region: "US")
    bibliography("references.bib")
}
```

You should be able to configurate a personal dictionary in your `./.helix/languages.toml` file or use the `options` argument, to load the configuration from a `json` file.

```toml
[language-server.typst-languagetool]
command = "typst-languagetool-lsp"

[language-server.typst-languagetool.config]
backend = "server"
host = "http://127.0.0.1"
port = "8081"

[language-server.typst-languagetool.config.dictionary]
en-US = ["a", "b", "c"]

[[language]]
name = "typst"
language-servers = ["typst-languagetool"]
```

I hope this works, but I did not test it in helix.
If the issue persists or another related problem arises, please reopen the issue.
